name: HTML to MP4

on:
  workflow_dispatch:
    inputs:
      html_content:
        description: "HTML snippet to render"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install tools (wkhtmltoimage + FFmpeg)
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf ffmpeg
          # wkhtmltoimage is part of wkhtmltopdf package

      - name: Save HTML to file
        run: |
          echo "${{ github.event.inputs.html_content }}" > input.html

      - name: Convert HTML to PNG
        run: wkhtmltoimage --width 1080 --height 1920 input.html input.png

      - name: Convert PNG to 5s MP4
        run: ffmpeg -loop 1 -i input.png -c:v libx264 -t 5 -pix_fmt yuv420p output.mp4

      # Save MP4 in repo (so it has a public URL via GitHub Pages if enabled)
      - name: Move output to public folder
        run: |
          mkdir -p public
          mv output.mp4 public/

      - name: Commit and push MP4
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add public/output.mp4
          git commit -m "Add new mp4"
          git push
