name: PNG to MP4

on:
  workflow_dispatch:
    inputs:
      image_url:
        description: "Source PNG URL"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg wget

      - name: Download PNG
        run: wget -O input.png "${{ github.event.inputs.image_url }}"

      - name: Generate MP4
        run: ffmpeg -loop 1 -i input.png -c:v libx264 -t 5 -pix_fmt yuv420p output.mp4

      # Save to repo (so it has a public raw URL)
      - name: Move output to public folder
        run: |
          mkdir -p public
          mv output.mp4 public/
      
      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add public/output.mp4
          git commit -m "Add new mp4"
          git push
